#Nginx Service

nginx:
    image: nginx:latest 
    container_name: webserver
    restart: unless-stopped
    build: ./nginx/
volumes:
    - ./default.conf /etc/nginx/conf.d/default.conf  
ports:
    - "80:80"
networks:
      - app-network   


#PHP Service
app:
  build:
    context: .
    dockerfile: Dockerfile
  image: digitalocean.com/php
  container_name: app
  restart: unless-stopped
  tty: true
  environment:
    SERVICE_NAME: app
    SERVICE_TAGS: dev
    working_dir: /var/www
  networks:
        - app-network
